name: Containre workflow
on: push

jobs:
  run_on_container:
    runs-on: ubuntu-latest
    container: node:13.5.0-alpine3.10
    steps:
      - name: Node version
        run: |
          node -v
          env
  
