name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo $GITHUB_REPOSITORY
          echo "${{ github }}"
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Powershell Directory
        run: Get-Location
      - name: Bash Directory
        run: pwd
        shell: bash
